name: Terraform Clumio

on:
  workflow_dispatch:   # manual trigger
  push:
    branches:
      - main           # or whichever branch should trigger

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 3.1.1   # pick a stable version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          TF_VAR_clumio_api_token: ${{ secrets.CLUMIO_API_TOKEN }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        env:
          TF_VAR_clumio_api_token: ${{ secrets.CLUMIO_API_TOKEN }}
        run: terraform apply -auto-approve tfplan
